/*
 * This source file was generated by the Gradle 'init' task
 */


import fishtank.FishTankClient;
import fishtank.FishTankServer;
import javafx.application.Application;

public class App {
    private static final int PORT = 8080;
    private static final int FISHTANK_PORT = 12346;
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        if (args.length > 0 && args[0].equalsIgnoreCase("fishtank-server")) {
            startFishTankServer();
        } else if (args.length > 0 && args[0].equalsIgnoreCase("fishtank-client")) {
            startFishTankClient(args);
        } else {
            System.out.println("Available commands:");
            System.out.println("  fishtank-server  - Start Fish Tank server");
            System.out.println("  fishtank-client  - Start Fish Tank client (JavaFX GUI)");
            System.out.println();
            System.out.println("Examples:");
            System.out.println("  java -jar FishTank.jar fishtank-server");
            System.out.println("  java -jar FishTank.jar fishtank-client");
        }
    }
    
    private static void startFishTankServer() {
        System.out.println("Starting Fish Tank Server...");
        try {
            FishTankServer server = new FishTankServer(FISHTANK_PORT);
            server.start();
            server.join(); // Wait for server to complete
        } catch (Exception e) {
            System.err.println("Failed to start fish tank server: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private static void startFishTankClient(String[] args) {
        System.out.println("Starting Fish Tank Client (JavaFX GUI)...");
        try {
            // Launch JavaFX application
            Application.launch(FishTankClient.class, args);
        } catch (Exception e) {
            System.err.println("Failed to start fish tank client: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
